# Book settings
title: Jose Bulux Portfolio
author: Jose Bulux
logo: logo.png


exclude_patterns            : ['data/*',  README.md, template_files/*]  #

# Execution settings
execute:
  allow_errors              : true
